FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /hive-server ./cmd/hive

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /hive-server /usr/local/bin/hive-server
ENTRYPOINT ["/usr/local/bin/hive-server", "-mode=server", "-config=/etc/hive/server_config.json"]
